# Generated by Django 4.1.2 on 2023-01-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.CharField(default='Rahul', max_length=2550),
        ),
    ]
