# Generated by Django 4.1.2 on 2023-01-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_order_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prod_price',
            field=models.FloatField(default=0),
        ),
    ]
